version: "3"
services:
  app:
    build: .
    volumes:
      - .:/repository
    ports:
      - "${APP_PORT}:8000"
    command:
      - /bin/bash
      - -c
      - uvicorn app.main:app --host 0.0.0.0 --port 8000
  datastore:
    image: postgres:latest
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      - POSTGRES_USER=${DS_USER}
      - POSTGRES_PASSWORD=${DS_PASSWORD}
      - POSTGRES_DB=${DS_DATABASE}
    ports:
      - "${DS_PORT}:5432"