@startuml packages
set namespaceSeparator none
package "app" as app {
}
package "app.inners" as app.inners {
}
package "app.inners.models" as app.inners.models {
}
package "app.inners.models.entities" as app.inners.models.entities {
}
package "app.inners.models.entities.account" as app.inners.models.entities.account {
}
package "app.inners.models.entities.base_entity" as app.inners.models.entities.base_entity {
}
package "app.inners.models.entities.company" as app.inners.models.entities.company {
}
package "app.inners.models.entities.file" as app.inners.models.entities.file {
}
package "app.inners.models.entities.inventory_control" as app.inners.models.entities.inventory_control {
}
package "app.inners.models.entities.item" as app.inners.models.entities.item {
}
package "app.inners.models.entities.item_bundle_map" as app.inners.models.entities.item_bundle_map {
}
package "app.inners.models.entities.item_file_map" as app.inners.models.entities.item_file_map {
}
package "app.inners.models.entities.location" as app.inners.models.entities.location {
}
package "app.inners.models.entities.role" as app.inners.models.entities.role {
}
package "app.inners.models.entities.transaction" as app.inners.models.entities.transaction {
}
package "app.inners.models.entities.transaction_item_map" as app.inners.models.entities.transaction_item_map {
}
package "app.inners.models.value_objects" as app.inners.models.value_objects {
}
package "app.inners.models.value_objects.base_value_object" as app.inners.models.value_objects.base_value_object {
}
package "app.inners.models.value_objects.contracts" as app.inners.models.value_objects.contracts {
}
package "app.inners.models.value_objects.contracts.requests" as app.inners.models.value_objects.contracts.requests {
}
package "app.inners.models.value_objects.contracts.requests.authentications" as app.inners.models.value_objects.contracts.requests.authentications {
}
package "app.inners.models.value_objects.contracts.requests.authentications.logins" as app.inners.models.value_objects.contracts.requests.authentications.logins {
}
package "app.inners.models.value_objects.contracts.requests.authentications.logins.login_by_email_and_password_body" as app.inners.models.value_objects.contracts.requests.authentications.logins.login_by_email_and_password_body {
}
package "app.inners.models.value_objects.contracts.requests.authentications.logins.login_by_email_and_password_request" as app.inners.models.value_objects.contracts.requests.authentications.logins.login_by_email_and_password_request {
}
package "app.inners.models.value_objects.contracts.requests.authentications.registers" as app.inners.models.value_objects.contracts.requests.authentications.registers {
}
package "app.inners.models.value_objects.contracts.requests.authentications.registers.account_register" as app.inners.models.value_objects.contracts.requests.authentications.registers.account_register {
}
package "app.inners.models.value_objects.contracts.requests.authentications.registers.company_register" as app.inners.models.value_objects.contracts.requests.authentications.registers.company_register {
}
package "app.inners.models.value_objects.contracts.requests.authentications.registers.location_register" as app.inners.models.value_objects.contracts.requests.authentications.registers.location_register {
}
package "app.inners.models.value_objects.contracts.requests.authentications.registers.register_by_email_and_password_body" as app.inners.models.value_objects.contracts.requests.authentications.registers.register_by_email_and_password_body {
}
package "app.inners.models.value_objects.contracts.requests.authentications.registers.register_by_email_and_password_request" as app.inners.models.value_objects.contracts.requests.authentications.registers.register_by_email_and_password_request {
}
package "app.inners.models.value_objects.contracts.requests.forecasts" as app.inners.models.value_objects.contracts.requests.forecasts {
}
package "app.inners.models.value_objects.contracts.requests.forecasts.item_stocks" as app.inners.models.value_objects.contracts.requests.forecasts.item_stocks {
}
package "app.inners.models.value_objects.contracts.requests.forecasts.item_stocks.stock_forecast_body" as app.inners.models.value_objects.contracts.requests.forecasts.item_stocks.stock_forecast_body {
}
package "app.inners.models.value_objects.contracts.requests.forecasts.item_stocks.stock_forecast_by_item_id_request" as app.inners.models.value_objects.contracts.requests.forecasts.item_stocks.stock_forecast_by_item_id_request {
}
package "app.inners.models.value_objects.contracts.requests.forecasts.item_transactions" as app.inners.models.value_objects.contracts.requests.forecasts.item_transactions {
}
package "app.inners.models.value_objects.contracts.requests.forecasts.item_transactions.transaction_forecast_body" as app.inners.models.value_objects.contracts.requests.forecasts.item_transactions.transaction_forecast_body {
}
package "app.inners.models.value_objects.contracts.requests.forecasts.item_transactions.transaction_forecast_by_item_id_request" as app.inners.models.value_objects.contracts.requests.forecasts.item_transactions.transaction_forecast_by_item_id_request {
}
package "app.inners.models.value_objects.contracts.requests.managements" as app.inners.models.value_objects.contracts.requests.managements {
}
package "app.inners.models.value_objects.contracts.requests.managements.accounts" as app.inners.models.value_objects.contracts.requests.managements.accounts {
}
package "app.inners.models.value_objects.contracts.requests.managements.accounts.create_body" as app.inners.models.value_objects.contracts.requests.managements.accounts.create_body {
}
package "app.inners.models.value_objects.contracts.requests.managements.accounts.create_one_request" as app.inners.models.value_objects.contracts.requests.managements.accounts.create_one_request {
}
package "app.inners.models.value_objects.contracts.requests.managements.accounts.delete_one_by_id_request" as app.inners.models.value_objects.contracts.requests.managements.accounts.delete_one_by_id_request {
}
package "app.inners.models.value_objects.contracts.requests.managements.accounts.patch_body" as app.inners.models.value_objects.contracts.requests.managements.accounts.patch_body {
}
package "app.inners.models.value_objects.contracts.requests.managements.accounts.patch_one_by_id_request" as app.inners.models.value_objects.contracts.requests.managements.accounts.patch_one_by_id_request {
}
package "app.inners.models.value_objects.contracts.requests.managements.accounts.read_all_by_company_id_request" as app.inners.models.value_objects.contracts.requests.managements.accounts.read_all_by_company_id_request {
}
package "app.inners.models.value_objects.contracts.requests.managements.accounts.read_all_request" as app.inners.models.value_objects.contracts.requests.managements.accounts.read_all_request {
}
package "app.inners.models.value_objects.contracts.requests.managements.accounts.read_one_by_id_request" as app.inners.models.value_objects.contracts.requests.managements.accounts.read_one_by_id_request {
}
package "app.inners.models.value_objects.contracts.requests.managements.companies" as app.inners.models.value_objects.contracts.requests.managements.companies {
}
package "app.inners.models.value_objects.contracts.requests.managements.companies.create_body" as app.inners.models.value_objects.contracts.requests.managements.companies.create_body {
}
package "app.inners.models.value_objects.contracts.requests.managements.companies.create_one_request" as app.inners.models.value_objects.contracts.requests.managements.companies.create_one_request {
}
package "app.inners.models.value_objects.contracts.requests.managements.companies.delete_one_by_id_request" as app.inners.models.value_objects.contracts.requests.managements.companies.delete_one_by_id_request {
}
package "app.inners.models.value_objects.contracts.requests.managements.companies.patch_body" as app.inners.models.value_objects.contracts.requests.managements.companies.patch_body {
}
package "app.inners.models.value_objects.contracts.requests.managements.companies.patch_one_by_id_request" as app.inners.models.value_objects.contracts.requests.managements.companies.patch_one_by_id_request {
}
package "app.inners.models.value_objects.contracts.requests.managements.companies.read_all_request" as app.inners.models.value_objects.contracts.requests.managements.companies.read_all_request {
}
package "app.inners.models.value_objects.contracts.requests.managements.companies.read_one_by_account_id_request" as app.inners.models.value_objects.contracts.requests.managements.companies.read_one_by_account_id_request {
}
package "app.inners.models.value_objects.contracts.requests.managements.companies.read_one_by_id_request" as app.inners.models.value_objects.contracts.requests.managements.companies.read_one_by_id_request {
}
package "app.inners.models.value_objects.contracts.requests.managements.files" as app.inners.models.value_objects.contracts.requests.managements.files {
}
package "app.inners.models.value_objects.contracts.requests.managements.files.create_body" as app.inners.models.value_objects.contracts.requests.managements.files.create_body {
}
package "app.inners.models.value_objects.contracts.requests.managements.files.create_one_request" as app.inners.models.value_objects.contracts.requests.managements.files.create_one_request {
}
package "app.inners.models.value_objects.contracts.requests.managements.files.delete_one_by_id_request" as app.inners.models.value_objects.contracts.requests.managements.files.delete_one_by_id_request {
}
package "app.inners.models.value_objects.contracts.requests.managements.files.patch_body" as app.inners.models.value_objects.contracts.requests.managements.files.patch_body {
}
package "app.inners.models.value_objects.contracts.requests.managements.files.patch_one_by_id_request" as app.inners.models.value_objects.contracts.requests.managements.files.patch_one_by_id_request {
}
package "app.inners.models.value_objects.contracts.requests.managements.files.read_all_request" as app.inners.models.value_objects.contracts.requests.managements.files.read_all_request {
}
package "app.inners.models.value_objects.contracts.requests.managements.files.read_one_by_id_request" as app.inners.models.value_objects.contracts.requests.managements.files.read_one_by_id_request {
}
package "app.inners.models.value_objects.contracts.requests.managements.inventory_controls" as app.inners.models.value_objects.contracts.requests.managements.inventory_controls {
}
package "app.inners.models.value_objects.contracts.requests.managements.inventory_controls.create_body" as app.inners.models.value_objects.contracts.requests.managements.inventory_controls.create_body {
}
package "app.inners.models.value_objects.contracts.requests.managements.inventory_controls.create_one_request" as app.inners.models.value_objects.contracts.requests.managements.inventory_controls.create_one_request {
}
package "app.inners.models.value_objects.contracts.requests.managements.inventory_controls.delete_one_by_id_request" as app.inners.models.value_objects.contracts.requests.managements.inventory_controls.delete_one_by_id_request {
}
package "app.inners.models.value_objects.contracts.requests.managements.inventory_controls.patch_body" as app.inners.models.value_objects.contracts.requests.managements.inventory_controls.patch_body {
}
package "app.inners.models.value_objects.contracts.requests.managements.inventory_controls.patch_one_by_id_request" as app.inners.models.value_objects.contracts.requests.managements.inventory_controls.patch_one_by_id_request {
}
package "app.inners.models.value_objects.contracts.requests.managements.inventory_controls.read_all_request" as app.inners.models.value_objects.contracts.requests.managements.inventory_controls.read_all_request {
}
package "app.inners.models.value_objects.contracts.requests.managements.inventory_controls.read_one_by_id_request" as app.inners.models.value_objects.contracts.requests.managements.inventory_controls.read_one_by_id_request {
}
package "app.inners.models.value_objects.contracts.requests.managements.item_bundle_maps" as app.inners.models.value_objects.contracts.requests.managements.item_bundle_maps {
}
package "app.inners.models.value_objects.contracts.requests.managements.item_bundle_maps.create_body" as app.inners.models.value_objects.contracts.requests.managements.item_bundle_maps.create_body {
}
package "app.inners.models.value_objects.contracts.requests.managements.item_bundle_maps.create_one_request" as app.inners.models.value_objects.contracts.requests.managements.item_bundle_maps.create_one_request {
}
package "app.inners.models.value_objects.contracts.requests.managements.item_bundle_maps.delete_one_by_id_request" as app.inners.models.value_objects.contracts.requests.managements.item_bundle_maps.delete_one_by_id_request {
}
package "app.inners.models.value_objects.contracts.requests.managements.item_bundle_maps.patch_body" as app.inners.models.value_objects.contracts.requests.managements.item_bundle_maps.patch_body {
}
package "app.inners.models.value_objects.contracts.requests.managements.item_bundle_maps.patch_one_by_id_request" as app.inners.models.value_objects.contracts.requests.managements.item_bundle_maps.patch_one_by_id_request {
}
package "app.inners.models.value_objects.contracts.requests.managements.item_bundle_maps.read_all_request" as app.inners.models.value_objects.contracts.requests.managements.item_bundle_maps.read_all_request {
}
package "app.inners.models.value_objects.contracts.requests.managements.item_bundle_maps.read_one_by_id_request" as app.inners.models.value_objects.contracts.requests.managements.item_bundle_maps.read_one_by_id_request {
}
package "app.inners.models.value_objects.contracts.requests.managements.item_file_maps" as app.inners.models.value_objects.contracts.requests.managements.item_file_maps {
}
package "app.inners.models.value_objects.contracts.requests.managements.item_file_maps.create_body" as app.inners.models.value_objects.contracts.requests.managements.item_file_maps.create_body {
}
package "app.inners.models.value_objects.contracts.requests.managements.item_file_maps.create_one_request" as app.inners.models.value_objects.contracts.requests.managements.item_file_maps.create_one_request {
}
package "app.inners.models.value_objects.contracts.requests.managements.item_file_maps.delete_one_by_id_request" as app.inners.models.value_objects.contracts.requests.managements.item_file_maps.delete_one_by_id_request {
}
package "app.inners.models.value_objects.contracts.requests.managements.item_file_maps.patch_body" as app.inners.models.value_objects.contracts.requests.managements.item_file_maps.patch_body {
}
package "app.inners.models.value_objects.contracts.requests.managements.item_file_maps.patch_one_by_id_request" as app.inners.models.value_objects.contracts.requests.managements.item_file_maps.patch_one_by_id_request {
}
package "app.inners.models.value_objects.contracts.requests.managements.item_file_maps.read_all_request" as app.inners.models.value_objects.contracts.requests.managements.item_file_maps.read_all_request {
}
package "app.inners.models.value_objects.contracts.requests.managements.item_file_maps.read_one_by_id_request" as app.inners.models.value_objects.contracts.requests.managements.item_file_maps.read_one_by_id_request {
}
package "app.inners.models.value_objects.contracts.requests.managements.items" as app.inners.models.value_objects.contracts.requests.managements.items {
}
package "app.inners.models.value_objects.contracts.requests.managements.items.create_body" as app.inners.models.value_objects.contracts.requests.managements.items.create_body {
}
package "app.inners.models.value_objects.contracts.requests.managements.items.create_one_request" as app.inners.models.value_objects.contracts.requests.managements.items.create_one_request {
}
package "app.inners.models.value_objects.contracts.requests.managements.items.delete_one_by_id_request" as app.inners.models.value_objects.contracts.requests.managements.items.delete_one_by_id_request {
}
package "app.inners.models.value_objects.contracts.requests.managements.items.patch_body" as app.inners.models.value_objects.contracts.requests.managements.items.patch_body {
}
package "app.inners.models.value_objects.contracts.requests.managements.items.patch_one_by_id_request" as app.inners.models.value_objects.contracts.requests.managements.items.patch_one_by_id_request {
}
package "app.inners.models.value_objects.contracts.requests.managements.items.read_all_request" as app.inners.models.value_objects.contracts.requests.managements.items.read_all_request {
}
package "app.inners.models.value_objects.contracts.requests.managements.items.read_one_by_id_request" as app.inners.models.value_objects.contracts.requests.managements.items.read_one_by_id_request {
}
package "app.inners.models.value_objects.contracts.requests.managements.locations" as app.inners.models.value_objects.contracts.requests.managements.locations {
}
package "app.inners.models.value_objects.contracts.requests.managements.locations.create_body" as app.inners.models.value_objects.contracts.requests.managements.locations.create_body {
}
package "app.inners.models.value_objects.contracts.requests.managements.locations.create_one_request" as app.inners.models.value_objects.contracts.requests.managements.locations.create_one_request {
}
package "app.inners.models.value_objects.contracts.requests.managements.locations.delete_one_by_id_request" as app.inners.models.value_objects.contracts.requests.managements.locations.delete_one_by_id_request {
}
package "app.inners.models.value_objects.contracts.requests.managements.locations.patch_body" as app.inners.models.value_objects.contracts.requests.managements.locations.patch_body {
}
package "app.inners.models.value_objects.contracts.requests.managements.locations.patch_one_by_id_request" as app.inners.models.value_objects.contracts.requests.managements.locations.patch_one_by_id_request {
}
package "app.inners.models.value_objects.contracts.requests.managements.locations.read_all_request" as app.inners.models.value_objects.contracts.requests.managements.locations.read_all_request {
}
package "app.inners.models.value_objects.contracts.requests.managements.locations.read_one_by_id_request" as app.inners.models.value_objects.contracts.requests.managements.locations.read_one_by_id_request {
}
package "app.inners.models.value_objects.contracts.requests.managements.roles" as app.inners.models.value_objects.contracts.requests.managements.roles {
}
package "app.inners.models.value_objects.contracts.requests.managements.roles.create_body" as app.inners.models.value_objects.contracts.requests.managements.roles.create_body {
}
package "app.inners.models.value_objects.contracts.requests.managements.roles.create_one_request" as app.inners.models.value_objects.contracts.requests.managements.roles.create_one_request {
}
package "app.inners.models.value_objects.contracts.requests.managements.roles.delete_one_by_id_request" as app.inners.models.value_objects.contracts.requests.managements.roles.delete_one_by_id_request {
}
package "app.inners.models.value_objects.contracts.requests.managements.roles.patch_body" as app.inners.models.value_objects.contracts.requests.managements.roles.patch_body {
}
package "app.inners.models.value_objects.contracts.requests.managements.roles.patch_one_by_id_request" as app.inners.models.value_objects.contracts.requests.managements.roles.patch_one_by_id_request {
}
package "app.inners.models.value_objects.contracts.requests.managements.roles.read_all_request" as app.inners.models.value_objects.contracts.requests.managements.roles.read_all_request {
}
package "app.inners.models.value_objects.contracts.requests.managements.roles.read_one_by_id_request" as app.inners.models.value_objects.contracts.requests.managements.roles.read_one_by_id_request {
}
package "app.inners.models.value_objects.contracts.requests.managements.transaction_item_maps" as app.inners.models.value_objects.contracts.requests.managements.transaction_item_maps {
}
package "app.inners.models.value_objects.contracts.requests.managements.transaction_item_maps.create_body" as app.inners.models.value_objects.contracts.requests.managements.transaction_item_maps.create_body {
}
package "app.inners.models.value_objects.contracts.requests.managements.transaction_item_maps.create_one_request" as app.inners.models.value_objects.contracts.requests.managements.transaction_item_maps.create_one_request {
}
package "app.inners.models.value_objects.contracts.requests.managements.transaction_item_maps.delete_one_by_id_request" as app.inners.models.value_objects.contracts.requests.managements.transaction_item_maps.delete_one_by_id_request {
}
package "app.inners.models.value_objects.contracts.requests.managements.transaction_item_maps.patch_body" as app.inners.models.value_objects.contracts.requests.managements.transaction_item_maps.patch_body {
}
package "app.inners.models.value_objects.contracts.requests.managements.transaction_item_maps.patch_one_by_id_request" as app.inners.models.value_objects.contracts.requests.managements.transaction_item_maps.patch_one_by_id_request {
}
package "app.inners.models.value_objects.contracts.requests.managements.transaction_item_maps.read_all_request" as app.inners.models.value_objects.contracts.requests.managements.transaction_item_maps.read_all_request {
}
package "app.inners.models.value_objects.contracts.requests.managements.transaction_item_maps.read_one_by_id_request" as app.inners.models.value_objects.contracts.requests.managements.transaction_item_maps.read_one_by_id_request {
}
package "app.inners.models.value_objects.contracts.requests.managements.transactions" as app.inners.models.value_objects.contracts.requests.managements.transactions {
}
package "app.inners.models.value_objects.contracts.requests.managements.transactions.create_body" as app.inners.models.value_objects.contracts.requests.managements.transactions.create_body {
}
package "app.inners.models.value_objects.contracts.requests.managements.transactions.create_one_request" as app.inners.models.value_objects.contracts.requests.managements.transactions.create_one_request {
}
package "app.inners.models.value_objects.contracts.requests.managements.transactions.delete_one_by_id_request" as app.inners.models.value_objects.contracts.requests.managements.transactions.delete_one_by_id_request {
}
package "app.inners.models.value_objects.contracts.requests.managements.transactions.patch_body" as app.inners.models.value_objects.contracts.requests.managements.transactions.patch_body {
}
package "app.inners.models.value_objects.contracts.requests.managements.transactions.patch_one_by_id_request" as app.inners.models.value_objects.contracts.requests.managements.transactions.patch_one_by_id_request {
}
package "app.inners.models.value_objects.contracts.requests.managements.transactions.read_all_request" as app.inners.models.value_objects.contracts.requests.managements.transactions.read_all_request {
}
package "app.inners.models.value_objects.contracts.requests.managements.transactions.read_one_by_id_request" as app.inners.models.value_objects.contracts.requests.managements.transactions.read_one_by_id_request {
}
package "app.inners.models.value_objects.contracts.responses" as app.inners.models.value_objects.contracts.responses {
}
package "app.inners.models.value_objects.contracts.responses.authentications" as app.inners.models.value_objects.contracts.responses.authentications {
}
package "app.inners.models.value_objects.contracts.responses.authentications.logins" as app.inners.models.value_objects.contracts.responses.authentications.logins {
}
package "app.inners.models.value_objects.contracts.responses.authentications.logins.login_response" as app.inners.models.value_objects.contracts.responses.authentications.logins.login_response {
}
package "app.inners.models.value_objects.contracts.responses.authentications.registers" as app.inners.models.value_objects.contracts.responses.authentications.registers {
}
package "app.inners.models.value_objects.contracts.responses.authentications.registers.register_response" as app.inners.models.value_objects.contracts.responses.authentications.registers.register_response {
}
package "app.inners.models.value_objects.contracts.responses.content" as app.inners.models.value_objects.contracts.responses.content {
}
package "app.inners.models.value_objects.contracts.responses.forecast" as app.inners.models.value_objects.contracts.responses.forecast {
}
package "app.inners.models.value_objects.contracts.responses.forecast.item_stock_forecast_response" as app.inners.models.value_objects.contracts.responses.forecast.item_stock_forecast_response {
}
package "app.inners.models.value_objects.contracts.responses.forecast.item_transaction_forecast_response" as app.inners.models.value_objects.contracts.responses.forecast.item_transaction_forecast_response {
}
package "app.inners.models.value_objects.forecasts" as app.inners.models.value_objects.forecasts {
}
package "app.inners.models.value_objects.forecasts.metric_forecast" as app.inners.models.value_objects.forecasts.metric_forecast {
}
package "app.inners.models.value_objects.forecasts.prediction_forecast" as app.inners.models.value_objects.forecasts.prediction_forecast {
}
package "app.inners.models.value_objects.forecasts.transaction_item_map_forecast" as app.inners.models.value_objects.forecasts.transaction_item_map_forecast {
}
package "app.inners.use_cases" as app.inners.use_cases {
}
package "app.inners.use_cases.authentications" as app.inners.use_cases.authentications {
}
package "app.inners.use_cases.authentications.login_authentication" as app.inners.use_cases.authentications.login_authentication {
}
package "app.inners.use_cases.authentications.register_authentication" as app.inners.use_cases.authentications.register_authentication {
}
package "app.inners.use_cases.forecasts" as app.inners.use_cases.forecasts {
}
package "app.inners.use_cases.forecasts.item_stock_forecast" as app.inners.use_cases.forecasts.item_stock_forecast {
}
package "app.inners.use_cases.forecasts.item_transaction_forecast" as app.inners.use_cases.forecasts.item_transaction_forecast {
}
package "app.inners.use_cases.managements" as app.inners.use_cases.managements {
}
package "app.inners.use_cases.managements.account_management" as app.inners.use_cases.managements.account_management {
}
package "app.inners.use_cases.managements.company_management" as app.inners.use_cases.managements.company_management {
}
package "app.inners.use_cases.managements.file_management" as app.inners.use_cases.managements.file_management {
}
package "app.inners.use_cases.managements.inventory_control_management" as app.inners.use_cases.managements.inventory_control_management {
}
package "app.inners.use_cases.managements.item_bundle_map_management" as app.inners.use_cases.managements.item_bundle_map_management {
}
package "app.inners.use_cases.managements.item_file_map_management" as app.inners.use_cases.managements.item_file_map_management {
}
package "app.inners.use_cases.managements.item_management" as app.inners.use_cases.managements.item_management {
}
package "app.inners.use_cases.managements.location_management" as app.inners.use_cases.managements.location_management {
}
package "app.inners.use_cases.managements.role_management" as app.inners.use_cases.managements.role_management {
}
package "app.inners.use_cases.managements.transaction_item_map_management" as app.inners.use_cases.managements.transaction_item_map_management {
}
package "app.inners.use_cases.managements.transaction_management" as app.inners.use_cases.managements.transaction_management {
}
package "app.main" as app.main {
}
package "app.outers" as app.outers {
}
package "app.outers.interfaces" as app.outers.interfaces {
}
package "app.outers.interfaces.deliveries" as app.outers.interfaces.deliveries {
}
package "app.outers.interfaces.deliveries.controllers" as app.outers.interfaces.deliveries.controllers {
}
package "app.outers.interfaces.deliveries.controllers.account_controller" as app.outers.interfaces.deliveries.controllers.account_controller {
}
package "app.outers.interfaces.deliveries.controllers.authentication_controller" as app.outers.interfaces.deliveries.controllers.authentication_controller {
}
package "app.outers.interfaces.deliveries.controllers.company_controller" as app.outers.interfaces.deliveries.controllers.company_controller {
}
package "app.outers.interfaces.deliveries.controllers.file_controller" as app.outers.interfaces.deliveries.controllers.file_controller {
}
package "app.outers.interfaces.deliveries.controllers.forecast_controller" as app.outers.interfaces.deliveries.controllers.forecast_controller {
}
package "app.outers.interfaces.deliveries.controllers.inventory_control_controller" as app.outers.interfaces.deliveries.controllers.inventory_control_controller {
}
package "app.outers.interfaces.deliveries.controllers.item_bundle_map_controller" as app.outers.interfaces.deliveries.controllers.item_bundle_map_controller {
}
package "app.outers.interfaces.deliveries.controllers.item_controller" as app.outers.interfaces.deliveries.controllers.item_controller {
}
package "app.outers.interfaces.deliveries.controllers.item_file_map_controller" as app.outers.interfaces.deliveries.controllers.item_file_map_controller {
}
package "app.outers.interfaces.deliveries.controllers.location_controller" as app.outers.interfaces.deliveries.controllers.location_controller {
}
package "app.outers.interfaces.deliveries.controllers.role_controller" as app.outers.interfaces.deliveries.controllers.role_controller {
}
package "app.outers.interfaces.deliveries.controllers.transaction_controller" as app.outers.interfaces.deliveries.controllers.transaction_controller {
}
package "app.outers.interfaces.deliveries.controllers.transaction_item_map_controller" as app.outers.interfaces.deliveries.controllers.transaction_item_map_controller {
}
package "app.outers.interfaces.deliveries.routers" as app.outers.interfaces.deliveries.routers {
}
package "app.outers.interfaces.deliveries.routers.api_router" as app.outers.interfaces.deliveries.routers.api_router {
}
package "app.outers.interfaces.deliveries.routers.api_v1_router" as app.outers.interfaces.deliveries.routers.api_v1_router {
}
package "app.outers.repositories" as app.outers.repositories {
}
package "app.outers.repositories.account_repository" as app.outers.repositories.account_repository {
}
package "app.outers.repositories.company_repository" as app.outers.repositories.company_repository {
}
package "app.outers.repositories.file_repository" as app.outers.repositories.file_repository {
}
package "app.outers.repositories.inventory_control_repository" as app.outers.repositories.inventory_control_repository {
}
package "app.outers.repositories.item_bundle_map_repository" as app.outers.repositories.item_bundle_map_repository {
}
package "app.outers.repositories.item_file_map_repository" as app.outers.repositories.item_file_map_repository {
}
package "app.outers.repositories.item_repository" as app.outers.repositories.item_repository {
}
package "app.outers.repositories.location_repository" as app.outers.repositories.location_repository {
}
package "app.outers.repositories.role_repository" as app.outers.repositories.role_repository {
}
package "app.outers.repositories.transaction_item_map_repository" as app.outers.repositories.transaction_item_map_repository {
}
package "app.outers.repositories.transaction_repository" as app.outers.repositories.transaction_repository {
}
package "app.outers.settings" as app.outers.settings {
}
package "app.outers.settings.datastore_settings" as app.outers.settings.datastore_settings {
}
package "app.outers.utilities" as app.outers.utilities {
}
package "app.outers.utilities.datastore_utility" as app.outers.utilities.datastore_utility {
}
package "app.outers.utilities.management_utility" as app.outers.utilities.management_utility {
}
app.inners.models.entities.account --> app.inners.models.entities.base_entity
app.inners.models.entities.company --> app.inners.models.entities.base_entity
app.inners.models.entities.file --> app.inners.models.entities.base_entity
app.inners.models.entities.inventory_control --> app.inners.models.entities.base_entity
app.inners.models.entities.item --> app.inners.models.entities.base_entity
app.inners.models.entities.item_bundle_map --> app.inners.models.entities.base_entity
app.inners.models.entities.item_file_map --> app.inners.models.entities.base_entity
app.inners.models.entities.location --> app.inners.models.entities.base_entity
app.inners.models.entities.role --> app.inners.models.entities.base_entity
app.inners.models.entities.transaction --> app.inners.models.entities.base_entity
app.inners.models.entities.transaction_item_map --> app.inners.models.entities.base_entity
app.inners.models.value_objects.contracts.requests.authentications.logins.login_by_email_and_password_body --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.authentications.logins.login_by_email_and_password_request --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.authentications.registers.account_register --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.authentications.registers.company_register --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.authentications.registers.location_register --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.authentications.registers.register_by_email_and_password_body --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.authentications.registers.register_by_email_and_password_body --> app.inners.models.value_objects.contracts.requests.authentications.registers.account_register
app.inners.models.value_objects.contracts.requests.authentications.registers.register_by_email_and_password_body --> app.inners.models.value_objects.contracts.requests.authentications.registers.company_register
app.inners.models.value_objects.contracts.requests.authentications.registers.register_by_email_and_password_body --> app.inners.models.value_objects.contracts.requests.authentications.registers.location_register
app.inners.models.value_objects.contracts.requests.authentications.registers.register_by_email_and_password_request --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.authentications.registers.register_by_email_and_password_request --> app.inners.models.value_objects.contracts.requests.authentications.registers.account_register
app.inners.models.value_objects.contracts.requests.authentications.registers.register_by_email_and_password_request --> app.inners.models.value_objects.contracts.requests.authentications.registers.company_register
app.inners.models.value_objects.contracts.requests.authentications.registers.register_by_email_and_password_request --> app.inners.models.value_objects.contracts.requests.authentications.registers.location_register
app.inners.models.value_objects.contracts.requests.forecasts.item_stocks.stock_forecast_body --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.forecasts.item_stocks.stock_forecast_by_item_id_request --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.forecasts.item_transactions.transaction_forecast_body --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.forecasts.item_transactions.transaction_forecast_by_item_id_request --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.accounts.create_body --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.accounts.create_one_request --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.accounts.create_one_request --> app.inners.models.value_objects.contracts.requests.managements.accounts.create_body
app.inners.models.value_objects.contracts.requests.managements.accounts.delete_one_by_id_request --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.accounts.patch_body --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.accounts.patch_one_by_id_request --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.accounts.patch_one_by_id_request --> app.inners.models.value_objects.contracts.requests.managements.accounts.patch_body
app.inners.models.value_objects.contracts.requests.managements.accounts.read_all_by_company_id_request --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.accounts.read_all_request --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.accounts.read_one_by_id_request --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.companies.create_body --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.companies.create_one_request --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.companies.create_one_request --> app.inners.models.value_objects.contracts.requests.managements.companies.create_body
app.inners.models.value_objects.contracts.requests.managements.companies.delete_one_by_id_request --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.companies.patch_body --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.companies.patch_one_by_id_request --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.companies.patch_one_by_id_request --> app.inners.models.value_objects.contracts.requests.managements.companies.patch_body
app.inners.models.value_objects.contracts.requests.managements.companies.read_all_request --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.companies.read_one_by_account_id_request --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.companies.read_one_by_id_request --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.files.create_body --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.files.create_one_request --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.files.create_one_request --> app.inners.models.value_objects.contracts.requests.managements.files.create_body
app.inners.models.value_objects.contracts.requests.managements.files.delete_one_by_id_request --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.files.patch_body --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.files.patch_one_by_id_request --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.files.patch_one_by_id_request --> app.inners.models.value_objects.contracts.requests.managements.files.patch_body
app.inners.models.value_objects.contracts.requests.managements.files.read_all_request --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.files.read_one_by_id_request --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.inventory_controls.create_body --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.inventory_controls.create_one_request --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.inventory_controls.create_one_request --> app.inners.models.value_objects.contracts.requests.managements.inventory_controls.create_body
app.inners.models.value_objects.contracts.requests.managements.inventory_controls.delete_one_by_id_request --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.inventory_controls.patch_body --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.inventory_controls.patch_one_by_id_request --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.inventory_controls.patch_one_by_id_request --> app.inners.models.value_objects.contracts.requests.managements.inventory_controls.patch_body
app.inners.models.value_objects.contracts.requests.managements.inventory_controls.read_all_request --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.inventory_controls.read_one_by_id_request --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.item_bundle_maps.create_body --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.item_bundle_maps.create_one_request --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.item_bundle_maps.create_one_request --> app.inners.models.value_objects.contracts.requests.managements.item_bundle_maps.create_body
app.inners.models.value_objects.contracts.requests.managements.item_bundle_maps.delete_one_by_id_request --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.item_bundle_maps.patch_body --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.item_bundle_maps.patch_one_by_id_request --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.item_bundle_maps.patch_one_by_id_request --> app.inners.models.value_objects.contracts.requests.managements.item_bundle_maps.patch_body
app.inners.models.value_objects.contracts.requests.managements.item_bundle_maps.read_all_request --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.item_bundle_maps.read_one_by_id_request --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.item_file_maps.create_body --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.item_file_maps.create_one_request --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.item_file_maps.create_one_request --> app.inners.models.value_objects.contracts.requests.managements.item_file_maps.create_body
app.inners.models.value_objects.contracts.requests.managements.item_file_maps.delete_one_by_id_request --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.item_file_maps.patch_body --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.item_file_maps.patch_one_by_id_request --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.item_file_maps.patch_one_by_id_request --> app.inners.models.value_objects.contracts.requests.managements.item_file_maps.patch_body
app.inners.models.value_objects.contracts.requests.managements.item_file_maps.read_all_request --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.item_file_maps.read_one_by_id_request --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.items.create_body --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.items.create_one_request --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.items.create_one_request --> app.inners.models.value_objects.contracts.requests.managements.items.create_body
app.inners.models.value_objects.contracts.requests.managements.items.delete_one_by_id_request --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.items.patch_body --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.items.patch_one_by_id_request --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.items.patch_one_by_id_request --> app.inners.models.value_objects.contracts.requests.managements.items.patch_body
app.inners.models.value_objects.contracts.requests.managements.items.read_all_request --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.items.read_one_by_id_request --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.locations.create_body --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.locations.create_one_request --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.locations.create_one_request --> app.inners.models.value_objects.contracts.requests.managements.locations.create_body
app.inners.models.value_objects.contracts.requests.managements.locations.delete_one_by_id_request --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.locations.patch_body --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.locations.patch_one_by_id_request --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.locations.patch_one_by_id_request --> app.inners.models.value_objects.contracts.requests.managements.locations.patch_body
app.inners.models.value_objects.contracts.requests.managements.locations.read_all_request --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.locations.read_one_by_id_request --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.roles.create_body --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.roles.create_one_request --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.roles.create_one_request --> app.inners.models.value_objects.contracts.requests.managements.roles.create_body
app.inners.models.value_objects.contracts.requests.managements.roles.delete_one_by_id_request --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.roles.patch_body --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.roles.patch_one_by_id_request --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.roles.patch_one_by_id_request --> app.inners.models.value_objects.contracts.requests.managements.roles.patch_body
app.inners.models.value_objects.contracts.requests.managements.roles.read_all_request --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.roles.read_one_by_id_request --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.transaction_item_maps.create_body --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.transaction_item_maps.create_one_request --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.transaction_item_maps.create_one_request --> app.inners.models.value_objects.contracts.requests.managements.transaction_item_maps.create_body
app.inners.models.value_objects.contracts.requests.managements.transaction_item_maps.delete_one_by_id_request --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.transaction_item_maps.patch_body --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.transaction_item_maps.patch_one_by_id_request --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.transaction_item_maps.patch_one_by_id_request --> app.inners.models.value_objects.contracts.requests.managements.transaction_item_maps.patch_body
app.inners.models.value_objects.contracts.requests.managements.transaction_item_maps.read_all_request --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.transaction_item_maps.read_one_by_id_request --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.transactions.create_body --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.transactions.create_one_request --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.transactions.create_one_request --> app.inners.models.value_objects.contracts.requests.managements.transactions.create_body
app.inners.models.value_objects.contracts.requests.managements.transactions.delete_one_by_id_request --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.transactions.patch_body --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.transactions.patch_one_by_id_request --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.transactions.patch_one_by_id_request --> app.inners.models.value_objects.contracts.requests.managements.transactions.patch_body
app.inners.models.value_objects.contracts.requests.managements.transactions.read_all_request --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.requests.managements.transactions.read_one_by_id_request --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.responses.authentications.logins.login_response --> app.inners.models.entities.account
app.inners.models.value_objects.contracts.responses.authentications.logins.login_response --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.responses.authentications.registers.register_response --> app.inners.models.entities.account
app.inners.models.value_objects.contracts.responses.authentications.registers.register_response --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.responses.content --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.responses.forecast.item_stock_forecast_response --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.responses.forecast.item_stock_forecast_response --> app.inners.models.value_objects.forecasts.metric_forecast
app.inners.models.value_objects.contracts.responses.forecast.item_stock_forecast_response --> app.inners.models.value_objects.forecasts.prediction_forecast
app.inners.models.value_objects.contracts.responses.forecast.item_transaction_forecast_response --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.contracts.responses.forecast.item_transaction_forecast_response --> app.inners.models.value_objects.forecasts.metric_forecast
app.inners.models.value_objects.contracts.responses.forecast.item_transaction_forecast_response --> app.inners.models.value_objects.forecasts.prediction_forecast
app.inners.models.value_objects.forecasts.metric_forecast --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.forecasts.prediction_forecast --> app.inners.models.value_objects.base_value_object
app.inners.models.value_objects.forecasts.transaction_item_map_forecast --> app.inners.models.value_objects.base_value_object
app.inners.use_cases.authentications.login_authentication --> app.inners.models.entities.account
app.inners.use_cases.authentications.login_authentication --> app.inners.models.value_objects.contracts.requests.authentications.logins.login_by_email_and_password_request
app.inners.use_cases.authentications.login_authentication --> app.inners.models.value_objects.contracts.responses.authentications.logins.login_response
app.inners.use_cases.authentications.login_authentication --> app.inners.models.value_objects.contracts.responses.content
app.inners.use_cases.authentications.login_authentication --> app.inners.use_cases.managements.account_management
app.inners.use_cases.authentications.register_authentication --> app.inners.models.entities.account
app.inners.use_cases.authentications.register_authentication --> app.inners.models.entities.role
app.inners.use_cases.authentications.register_authentication --> app.inners.models.value_objects.contracts.requests.authentications.registers.register_by_email_and_password_request
app.inners.use_cases.authentications.register_authentication --> app.inners.models.value_objects.contracts.requests.managements.accounts.create_body
app.inners.use_cases.authentications.register_authentication --> app.inners.models.value_objects.contracts.requests.managements.accounts.create_one_request
app.inners.use_cases.authentications.register_authentication --> app.inners.models.value_objects.contracts.requests.managements.companies.create_body
app.inners.use_cases.authentications.register_authentication --> app.inners.models.value_objects.contracts.requests.managements.companies.create_one_request
app.inners.use_cases.authentications.register_authentication --> app.inners.models.value_objects.contracts.requests.managements.locations.create_body
app.inners.use_cases.authentications.register_authentication --> app.inners.models.value_objects.contracts.requests.managements.locations.create_one_request
app.inners.use_cases.authentications.register_authentication --> app.inners.models.value_objects.contracts.requests.managements.roles.read_all_request
app.inners.use_cases.authentications.register_authentication --> app.inners.models.value_objects.contracts.responses.authentications.registers.register_response
app.inners.use_cases.authentications.register_authentication --> app.inners.models.value_objects.contracts.responses.content
app.inners.use_cases.authentications.register_authentication --> app.inners.use_cases.managements.account_management
app.inners.use_cases.authentications.register_authentication --> app.inners.use_cases.managements.company_management
app.inners.use_cases.authentications.register_authentication --> app.inners.use_cases.managements.location_management
app.inners.use_cases.authentications.register_authentication --> app.inners.use_cases.managements.role_management
app.inners.use_cases.forecasts.item_stock_forecast --> app.inners.models.entities.inventory_control
app.inners.use_cases.forecasts.item_stock_forecast --> app.inners.models.value_objects.contracts.requests.forecasts.item_stocks.stock_forecast_by_item_id_request
app.inners.use_cases.forecasts.item_stock_forecast --> app.inners.models.value_objects.contracts.responses.content
app.inners.use_cases.forecasts.item_stock_forecast --> app.inners.models.value_objects.contracts.responses.forecast.item_stock_forecast_response
app.inners.use_cases.forecasts.item_stock_forecast --> app.inners.models.value_objects.forecasts.metric_forecast
app.inners.use_cases.forecasts.item_stock_forecast --> app.inners.models.value_objects.forecasts.prediction_forecast
app.inners.use_cases.forecasts.item_stock_forecast --> app.outers.repositories.inventory_control_repository
app.inners.use_cases.forecasts.item_transaction_forecast --> app.inners.models.value_objects.contracts.requests.forecasts.item_transactions.transaction_forecast_by_item_id_request
app.inners.use_cases.forecasts.item_transaction_forecast --> app.inners.models.value_objects.contracts.responses.content
app.inners.use_cases.forecasts.item_transaction_forecast --> app.inners.models.value_objects.contracts.responses.forecast.item_transaction_forecast_response
app.inners.use_cases.forecasts.item_transaction_forecast --> app.inners.models.value_objects.forecasts.metric_forecast
app.inners.use_cases.forecasts.item_transaction_forecast --> app.inners.models.value_objects.forecasts.prediction_forecast
app.inners.use_cases.forecasts.item_transaction_forecast --> app.inners.models.value_objects.forecasts.transaction_item_map_forecast
app.inners.use_cases.forecasts.item_transaction_forecast --> app.outers.repositories.transaction_item_map_repository
app.inners.use_cases.managements.account_management --> app.inners.models.entities.account
app.inners.use_cases.managements.account_management --> app.inners.models.value_objects.contracts.requests.managements.accounts.create_one_request
app.inners.use_cases.managements.account_management --> app.inners.models.value_objects.contracts.requests.managements.accounts.delete_one_by_id_request
app.inners.use_cases.managements.account_management --> app.inners.models.value_objects.contracts.requests.managements.accounts.patch_one_by_id_request
app.inners.use_cases.managements.account_management --> app.inners.models.value_objects.contracts.requests.managements.accounts.read_all_by_company_id_request
app.inners.use_cases.managements.account_management --> app.inners.models.value_objects.contracts.requests.managements.accounts.read_all_request
app.inners.use_cases.managements.account_management --> app.inners.models.value_objects.contracts.requests.managements.accounts.read_one_by_id_request
app.inners.use_cases.managements.account_management --> app.inners.models.value_objects.contracts.responses.content
app.inners.use_cases.managements.account_management --> app.outers.repositories.account_repository
app.inners.use_cases.managements.account_management --> app.outers.utilities.management_utility
app.inners.use_cases.managements.company_management --> app.inners.models.entities.company
app.inners.use_cases.managements.company_management --> app.inners.models.value_objects.contracts.requests.managements.companies.create_one_request
app.inners.use_cases.managements.company_management --> app.inners.models.value_objects.contracts.requests.managements.companies.delete_one_by_id_request
app.inners.use_cases.managements.company_management --> app.inners.models.value_objects.contracts.requests.managements.companies.patch_one_by_id_request
app.inners.use_cases.managements.company_management --> app.inners.models.value_objects.contracts.requests.managements.companies.read_all_request
app.inners.use_cases.managements.company_management --> app.inners.models.value_objects.contracts.requests.managements.companies.read_one_by_id_request
app.inners.use_cases.managements.company_management --> app.inners.models.value_objects.contracts.responses.content
app.inners.use_cases.managements.company_management --> app.outers.repositories.company_repository
app.inners.use_cases.managements.company_management --> app.outers.utilities.management_utility
app.inners.use_cases.managements.file_management --> app.inners.models.entities.file
app.inners.use_cases.managements.file_management --> app.inners.models.value_objects.contracts.requests.managements.files.create_one_request
app.inners.use_cases.managements.file_management --> app.inners.models.value_objects.contracts.requests.managements.files.delete_one_by_id_request
app.inners.use_cases.managements.file_management --> app.inners.models.value_objects.contracts.requests.managements.files.patch_one_by_id_request
app.inners.use_cases.managements.file_management --> app.inners.models.value_objects.contracts.requests.managements.files.read_all_request
app.inners.use_cases.managements.file_management --> app.inners.models.value_objects.contracts.requests.managements.files.read_one_by_id_request
app.inners.use_cases.managements.file_management --> app.inners.models.value_objects.contracts.responses.content
app.inners.use_cases.managements.file_management --> app.outers.repositories.file_repository
app.inners.use_cases.managements.file_management --> app.outers.utilities.management_utility
app.inners.use_cases.managements.inventory_control_management --> app.inners.models.entities.inventory_control
app.inners.use_cases.managements.inventory_control_management --> app.inners.models.value_objects.contracts.requests.managements.inventory_controls.create_one_request
app.inners.use_cases.managements.inventory_control_management --> app.inners.models.value_objects.contracts.requests.managements.inventory_controls.delete_one_by_id_request
app.inners.use_cases.managements.inventory_control_management --> app.inners.models.value_objects.contracts.requests.managements.inventory_controls.patch_one_by_id_request
app.inners.use_cases.managements.inventory_control_management --> app.inners.models.value_objects.contracts.requests.managements.inventory_controls.read_all_request
app.inners.use_cases.managements.inventory_control_management --> app.inners.models.value_objects.contracts.requests.managements.inventory_controls.read_one_by_id_request
app.inners.use_cases.managements.inventory_control_management --> app.inners.models.value_objects.contracts.responses.content
app.inners.use_cases.managements.inventory_control_management --> app.outers.repositories.inventory_control_repository
app.inners.use_cases.managements.inventory_control_management --> app.outers.utilities.management_utility
app.inners.use_cases.managements.item_bundle_map_management --> app.inners.models.entities.item_bundle_map
app.inners.use_cases.managements.item_bundle_map_management --> app.inners.models.value_objects.contracts.requests.managements.item_bundle_maps.create_one_request
app.inners.use_cases.managements.item_bundle_map_management --> app.inners.models.value_objects.contracts.requests.managements.item_bundle_maps.delete_one_by_id_request
app.inners.use_cases.managements.item_bundle_map_management --> app.inners.models.value_objects.contracts.requests.managements.item_bundle_maps.patch_one_by_id_request
app.inners.use_cases.managements.item_bundle_map_management --> app.inners.models.value_objects.contracts.requests.managements.item_bundle_maps.read_all_request
app.inners.use_cases.managements.item_bundle_map_management --> app.inners.models.value_objects.contracts.requests.managements.item_bundle_maps.read_one_by_id_request
app.inners.use_cases.managements.item_bundle_map_management --> app.inners.models.value_objects.contracts.responses.content
app.inners.use_cases.managements.item_bundle_map_management --> app.outers.repositories.item_bundle_map_repository
app.inners.use_cases.managements.item_bundle_map_management --> app.outers.utilities.management_utility
app.inners.use_cases.managements.item_file_map_management --> app.inners.models.entities.item_file_map
app.inners.use_cases.managements.item_file_map_management --> app.inners.models.value_objects.contracts.requests.managements.item_file_maps.create_one_request
app.inners.use_cases.managements.item_file_map_management --> app.inners.models.value_objects.contracts.requests.managements.item_file_maps.delete_one_by_id_request
app.inners.use_cases.managements.item_file_map_management --> app.inners.models.value_objects.contracts.requests.managements.item_file_maps.patch_one_by_id_request
app.inners.use_cases.managements.item_file_map_management --> app.inners.models.value_objects.contracts.requests.managements.item_file_maps.read_all_request
app.inners.use_cases.managements.item_file_map_management --> app.inners.models.value_objects.contracts.requests.managements.item_file_maps.read_one_by_id_request
app.inners.use_cases.managements.item_file_map_management --> app.inners.models.value_objects.contracts.responses.content
app.inners.use_cases.managements.item_file_map_management --> app.outers.repositories.item_file_map_repository
app.inners.use_cases.managements.item_file_map_management --> app.outers.utilities.management_utility
app.inners.use_cases.managements.item_management --> app.inners.models.entities.item
app.inners.use_cases.managements.item_management --> app.inners.models.value_objects.contracts.requests.managements.item_file_maps.read_all_request
app.inners.use_cases.managements.item_management --> app.inners.models.value_objects.contracts.requests.managements.items.create_one_request
app.inners.use_cases.managements.item_management --> app.inners.models.value_objects.contracts.requests.managements.items.delete_one_by_id_request
app.inners.use_cases.managements.item_management --> app.inners.models.value_objects.contracts.requests.managements.items.patch_one_by_id_request
app.inners.use_cases.managements.item_management --> app.inners.models.value_objects.contracts.requests.managements.items.read_one_by_id_request
app.inners.use_cases.managements.item_management --> app.inners.models.value_objects.contracts.responses.content
app.inners.use_cases.managements.item_management --> app.outers.repositories.item_repository
app.inners.use_cases.managements.item_management --> app.outers.utilities.management_utility
app.inners.use_cases.managements.location_management --> app.inners.models.entities.location
app.inners.use_cases.managements.location_management --> app.inners.models.value_objects.contracts.requests.managements.locations.create_one_request
app.inners.use_cases.managements.location_management --> app.inners.models.value_objects.contracts.requests.managements.locations.delete_one_by_id_request
app.inners.use_cases.managements.location_management --> app.inners.models.value_objects.contracts.requests.managements.locations.patch_one_by_id_request
app.inners.use_cases.managements.location_management --> app.inners.models.value_objects.contracts.requests.managements.locations.read_all_request
app.inners.use_cases.managements.location_management --> app.inners.models.value_objects.contracts.requests.managements.locations.read_one_by_id_request
app.inners.use_cases.managements.location_management --> app.inners.models.value_objects.contracts.responses.content
app.inners.use_cases.managements.location_management --> app.outers.repositories.location_repository
app.inners.use_cases.managements.location_management --> app.outers.utilities.management_utility
app.inners.use_cases.managements.role_management --> app.inners.models.entities.role
app.inners.use_cases.managements.role_management --> app.inners.models.value_objects.contracts.requests.managements.roles.create_one_request
app.inners.use_cases.managements.role_management --> app.inners.models.value_objects.contracts.requests.managements.roles.delete_one_by_id_request
app.inners.use_cases.managements.role_management --> app.inners.models.value_objects.contracts.requests.managements.roles.patch_one_by_id_request
app.inners.use_cases.managements.role_management --> app.inners.models.value_objects.contracts.requests.managements.roles.read_all_request
app.inners.use_cases.managements.role_management --> app.inners.models.value_objects.contracts.requests.managements.roles.read_one_by_id_request
app.inners.use_cases.managements.role_management --> app.inners.models.value_objects.contracts.responses.content
app.inners.use_cases.managements.role_management --> app.outers.repositories.role_repository
app.inners.use_cases.managements.role_management --> app.outers.utilities.management_utility
app.inners.use_cases.managements.transaction_item_map_management --> app.inners.models.entities.transaction_item_map
app.inners.use_cases.managements.transaction_item_map_management --> app.inners.models.value_objects.contracts.requests.managements.transaction_item_maps.delete_one_by_id_request
app.inners.use_cases.managements.transaction_item_map_management --> app.inners.models.value_objects.contracts.requests.managements.transaction_item_maps.read_one_by_id_request
app.inners.use_cases.managements.transaction_item_map_management --> app.inners.models.value_objects.contracts.requests.managements.transactions.create_one_request
app.inners.use_cases.managements.transaction_item_map_management --> app.inners.models.value_objects.contracts.requests.managements.transactions.patch_one_by_id_request
app.inners.use_cases.managements.transaction_item_map_management --> app.inners.models.value_objects.contracts.requests.managements.transactions.read_all_request
app.inners.use_cases.managements.transaction_item_map_management --> app.inners.models.value_objects.contracts.responses.content
app.inners.use_cases.managements.transaction_item_map_management --> app.outers.repositories.transaction_item_map_repository
app.inners.use_cases.managements.transaction_item_map_management --> app.outers.utilities.management_utility
app.inners.use_cases.managements.transaction_management --> app.inners.models.entities.transaction
app.inners.use_cases.managements.transaction_management --> app.inners.models.value_objects.contracts.requests.managements.transactions.create_one_request
app.inners.use_cases.managements.transaction_management --> app.inners.models.value_objects.contracts.requests.managements.transactions.delete_one_by_id_request
app.inners.use_cases.managements.transaction_management --> app.inners.models.value_objects.contracts.requests.managements.transactions.patch_one_by_id_request
app.inners.use_cases.managements.transaction_management --> app.inners.models.value_objects.contracts.requests.managements.transactions.read_all_request
app.inners.use_cases.managements.transaction_management --> app.inners.models.value_objects.contracts.requests.managements.transactions.read_one_by_id_request
app.inners.use_cases.managements.transaction_management --> app.inners.models.value_objects.contracts.responses.content
app.inners.use_cases.managements.transaction_management --> app.outers.repositories.transaction_repository
app.inners.use_cases.managements.transaction_management --> app.outers.utilities.management_utility
app.main --> app.outers.interfaces.deliveries.routers.api_router
app.outers.interfaces.deliveries.controllers.account_controller --> app.inners.models.entities.account
app.outers.interfaces.deliveries.controllers.account_controller --> app.inners.models.value_objects.contracts.requests.managements.accounts.create_body
app.outers.interfaces.deliveries.controllers.account_controller --> app.inners.models.value_objects.contracts.requests.managements.accounts.create_one_request
app.outers.interfaces.deliveries.controllers.account_controller --> app.inners.models.value_objects.contracts.requests.managements.accounts.delete_one_by_id_request
app.outers.interfaces.deliveries.controllers.account_controller --> app.inners.models.value_objects.contracts.requests.managements.accounts.patch_body
app.outers.interfaces.deliveries.controllers.account_controller --> app.inners.models.value_objects.contracts.requests.managements.accounts.patch_one_by_id_request
app.outers.interfaces.deliveries.controllers.account_controller --> app.inners.models.value_objects.contracts.requests.managements.accounts.read_all_request
app.outers.interfaces.deliveries.controllers.account_controller --> app.inners.models.value_objects.contracts.requests.managements.accounts.read_one_by_id_request
app.outers.interfaces.deliveries.controllers.account_controller --> app.inners.models.value_objects.contracts.responses.content
app.outers.interfaces.deliveries.controllers.account_controller --> app.inners.use_cases.managements.account_management
app.outers.interfaces.deliveries.controllers.authentication_controller --> app.inners.models.value_objects.contracts.requests.authentications.logins.login_by_email_and_password_body
app.outers.interfaces.deliveries.controllers.authentication_controller --> app.inners.models.value_objects.contracts.requests.authentications.logins.login_by_email_and_password_request
app.outers.interfaces.deliveries.controllers.authentication_controller --> app.inners.models.value_objects.contracts.requests.authentications.registers.register_by_email_and_password_body
app.outers.interfaces.deliveries.controllers.authentication_controller --> app.inners.models.value_objects.contracts.requests.authentications.registers.register_by_email_and_password_request
app.outers.interfaces.deliveries.controllers.authentication_controller --> app.inners.models.value_objects.contracts.responses.authentications.logins.login_response
app.outers.interfaces.deliveries.controllers.authentication_controller --> app.inners.models.value_objects.contracts.responses.authentications.registers.register_response
app.outers.interfaces.deliveries.controllers.authentication_controller --> app.inners.models.value_objects.contracts.responses.content
app.outers.interfaces.deliveries.controllers.authentication_controller --> app.inners.use_cases.authentications.login_authentication
app.outers.interfaces.deliveries.controllers.authentication_controller --> app.inners.use_cases.authentications.register_authentication
app.outers.interfaces.deliveries.controllers.company_controller --> app.inners.models.entities.company
app.outers.interfaces.deliveries.controllers.company_controller --> app.inners.models.value_objects.contracts.requests.managements.companies.create_body
app.outers.interfaces.deliveries.controllers.company_controller --> app.inners.models.value_objects.contracts.requests.managements.companies.create_one_request
app.outers.interfaces.deliveries.controllers.company_controller --> app.inners.models.value_objects.contracts.requests.managements.companies.delete_one_by_id_request
app.outers.interfaces.deliveries.controllers.company_controller --> app.inners.models.value_objects.contracts.requests.managements.companies.patch_body
app.outers.interfaces.deliveries.controllers.company_controller --> app.inners.models.value_objects.contracts.requests.managements.companies.patch_one_by_id_request
app.outers.interfaces.deliveries.controllers.company_controller --> app.inners.models.value_objects.contracts.requests.managements.companies.read_all_request
app.outers.interfaces.deliveries.controllers.company_controller --> app.inners.models.value_objects.contracts.requests.managements.companies.read_one_by_id_request
app.outers.interfaces.deliveries.controllers.company_controller --> app.inners.models.value_objects.contracts.responses.content
app.outers.interfaces.deliveries.controllers.company_controller --> app.inners.use_cases.managements.company_management
app.outers.interfaces.deliveries.controllers.file_controller --> app.inners.models.entities.file
app.outers.interfaces.deliveries.controllers.file_controller --> app.inners.models.value_objects.contracts.requests.managements.files.create_body
app.outers.interfaces.deliveries.controllers.file_controller --> app.inners.models.value_objects.contracts.requests.managements.files.create_one_request
app.outers.interfaces.deliveries.controllers.file_controller --> app.inners.models.value_objects.contracts.requests.managements.files.delete_one_by_id_request
app.outers.interfaces.deliveries.controllers.file_controller --> app.inners.models.value_objects.contracts.requests.managements.files.patch_body
app.outers.interfaces.deliveries.controllers.file_controller --> app.inners.models.value_objects.contracts.requests.managements.files.patch_one_by_id_request
app.outers.interfaces.deliveries.controllers.file_controller --> app.inners.models.value_objects.contracts.requests.managements.files.read_all_request
app.outers.interfaces.deliveries.controllers.file_controller --> app.inners.models.value_objects.contracts.requests.managements.files.read_one_by_id_request
app.outers.interfaces.deliveries.controllers.file_controller --> app.inners.models.value_objects.contracts.responses.content
app.outers.interfaces.deliveries.controllers.file_controller --> app.inners.use_cases.managements.file_management
app.outers.interfaces.deliveries.controllers.forecast_controller --> app.inners.models.value_objects.contracts.requests.forecasts.item_stocks.stock_forecast_body
app.outers.interfaces.deliveries.controllers.forecast_controller --> app.inners.models.value_objects.contracts.requests.forecasts.item_stocks.stock_forecast_by_item_id_request
app.outers.interfaces.deliveries.controllers.forecast_controller --> app.inners.models.value_objects.contracts.requests.forecasts.item_transactions.transaction_forecast_body
app.outers.interfaces.deliveries.controllers.forecast_controller --> app.inners.models.value_objects.contracts.requests.forecasts.item_transactions.transaction_forecast_by_item_id_request
app.outers.interfaces.deliveries.controllers.forecast_controller --> app.inners.models.value_objects.contracts.responses.content
app.outers.interfaces.deliveries.controllers.forecast_controller --> app.inners.models.value_objects.contracts.responses.forecast.item_stock_forecast_response
app.outers.interfaces.deliveries.controllers.forecast_controller --> app.inners.models.value_objects.contracts.responses.forecast.item_transaction_forecast_response
app.outers.interfaces.deliveries.controllers.forecast_controller --> app.inners.use_cases.forecasts.item_stock_forecast
app.outers.interfaces.deliveries.controllers.forecast_controller --> app.inners.use_cases.forecasts.item_transaction_forecast
app.outers.interfaces.deliveries.controllers.inventory_control_controller --> app.inners.models.entities.inventory_control
app.outers.interfaces.deliveries.controllers.inventory_control_controller --> app.inners.models.value_objects.contracts.requests.managements.inventory_controls.create_body
app.outers.interfaces.deliveries.controllers.inventory_control_controller --> app.inners.models.value_objects.contracts.requests.managements.inventory_controls.create_one_request
app.outers.interfaces.deliveries.controllers.inventory_control_controller --> app.inners.models.value_objects.contracts.requests.managements.inventory_controls.delete_one_by_id_request
app.outers.interfaces.deliveries.controllers.inventory_control_controller --> app.inners.models.value_objects.contracts.requests.managements.inventory_controls.patch_body
app.outers.interfaces.deliveries.controllers.inventory_control_controller --> app.inners.models.value_objects.contracts.requests.managements.inventory_controls.patch_one_by_id_request
app.outers.interfaces.deliveries.controllers.inventory_control_controller --> app.inners.models.value_objects.contracts.requests.managements.inventory_controls.read_all_request
app.outers.interfaces.deliveries.controllers.inventory_control_controller --> app.inners.models.value_objects.contracts.requests.managements.inventory_controls.read_one_by_id_request
app.outers.interfaces.deliveries.controllers.inventory_control_controller --> app.inners.models.value_objects.contracts.responses.content
app.outers.interfaces.deliveries.controllers.inventory_control_controller --> app.inners.use_cases.managements.inventory_control_management
app.outers.interfaces.deliveries.controllers.item_bundle_map_controller --> app.inners.models.entities.item_bundle_map
app.outers.interfaces.deliveries.controllers.item_bundle_map_controller --> app.inners.models.value_objects.contracts.requests.managements.item_bundle_maps.create_body
app.outers.interfaces.deliveries.controllers.item_bundle_map_controller --> app.inners.models.value_objects.contracts.requests.managements.item_bundle_maps.create_one_request
app.outers.interfaces.deliveries.controllers.item_bundle_map_controller --> app.inners.models.value_objects.contracts.requests.managements.item_bundle_maps.delete_one_by_id_request
app.outers.interfaces.deliveries.controllers.item_bundle_map_controller --> app.inners.models.value_objects.contracts.requests.managements.item_bundle_maps.patch_body
app.outers.interfaces.deliveries.controllers.item_bundle_map_controller --> app.inners.models.value_objects.contracts.requests.managements.item_bundle_maps.patch_one_by_id_request
app.outers.interfaces.deliveries.controllers.item_bundle_map_controller --> app.inners.models.value_objects.contracts.requests.managements.item_bundle_maps.read_all_request
app.outers.interfaces.deliveries.controllers.item_bundle_map_controller --> app.inners.models.value_objects.contracts.requests.managements.item_bundle_maps.read_one_by_id_request
app.outers.interfaces.deliveries.controllers.item_bundle_map_controller --> app.inners.models.value_objects.contracts.responses.content
app.outers.interfaces.deliveries.controllers.item_bundle_map_controller --> app.inners.use_cases.managements.item_bundle_map_management
app.outers.interfaces.deliveries.controllers.item_controller --> app.inners.models.entities.item
app.outers.interfaces.deliveries.controllers.item_controller --> app.inners.models.value_objects.contracts.requests.managements.item_file_maps.read_all_request
app.outers.interfaces.deliveries.controllers.item_controller --> app.inners.models.value_objects.contracts.requests.managements.items.create_body
app.outers.interfaces.deliveries.controllers.item_controller --> app.inners.models.value_objects.contracts.requests.managements.items.create_one_request
app.outers.interfaces.deliveries.controllers.item_controller --> app.inners.models.value_objects.contracts.requests.managements.items.delete_one_by_id_request
app.outers.interfaces.deliveries.controllers.item_controller --> app.inners.models.value_objects.contracts.requests.managements.items.patch_body
app.outers.interfaces.deliveries.controllers.item_controller --> app.inners.models.value_objects.contracts.requests.managements.items.patch_one_by_id_request
app.outers.interfaces.deliveries.controllers.item_controller --> app.inners.models.value_objects.contracts.requests.managements.items.read_one_by_id_request
app.outers.interfaces.deliveries.controllers.item_controller --> app.inners.models.value_objects.contracts.responses.content
app.outers.interfaces.deliveries.controllers.item_controller --> app.inners.use_cases.managements.item_management
app.outers.interfaces.deliveries.controllers.item_file_map_controller --> app.inners.models.entities.item_file_map
app.outers.interfaces.deliveries.controllers.item_file_map_controller --> app.inners.models.value_objects.contracts.requests.managements.item_file_maps.create_body
app.outers.interfaces.deliveries.controllers.item_file_map_controller --> app.inners.models.value_objects.contracts.requests.managements.item_file_maps.create_one_request
app.outers.interfaces.deliveries.controllers.item_file_map_controller --> app.inners.models.value_objects.contracts.requests.managements.item_file_maps.delete_one_by_id_request
app.outers.interfaces.deliveries.controllers.item_file_map_controller --> app.inners.models.value_objects.contracts.requests.managements.item_file_maps.patch_body
app.outers.interfaces.deliveries.controllers.item_file_map_controller --> app.inners.models.value_objects.contracts.requests.managements.item_file_maps.patch_one_by_id_request
app.outers.interfaces.deliveries.controllers.item_file_map_controller --> app.inners.models.value_objects.contracts.requests.managements.item_file_maps.read_all_request
app.outers.interfaces.deliveries.controllers.item_file_map_controller --> app.inners.models.value_objects.contracts.requests.managements.item_file_maps.read_one_by_id_request
app.outers.interfaces.deliveries.controllers.item_file_map_controller --> app.inners.models.value_objects.contracts.responses.content
app.outers.interfaces.deliveries.controllers.item_file_map_controller --> app.inners.use_cases.managements.item_file_map_management
app.outers.interfaces.deliveries.controllers.location_controller --> app.inners.models.entities.location
app.outers.interfaces.deliveries.controllers.location_controller --> app.inners.models.value_objects.contracts.requests.managements.locations.create_body
app.outers.interfaces.deliveries.controllers.location_controller --> app.inners.models.value_objects.contracts.requests.managements.locations.create_one_request
app.outers.interfaces.deliveries.controllers.location_controller --> app.inners.models.value_objects.contracts.requests.managements.locations.delete_one_by_id_request
app.outers.interfaces.deliveries.controllers.location_controller --> app.inners.models.value_objects.contracts.requests.managements.locations.patch_body
app.outers.interfaces.deliveries.controllers.location_controller --> app.inners.models.value_objects.contracts.requests.managements.locations.patch_one_by_id_request
app.outers.interfaces.deliveries.controllers.location_controller --> app.inners.models.value_objects.contracts.requests.managements.locations.read_all_request
app.outers.interfaces.deliveries.controllers.location_controller --> app.inners.models.value_objects.contracts.requests.managements.locations.read_one_by_id_request
app.outers.interfaces.deliveries.controllers.location_controller --> app.inners.models.value_objects.contracts.responses.content
app.outers.interfaces.deliveries.controllers.location_controller --> app.inners.use_cases.managements.location_management
app.outers.interfaces.deliveries.controllers.role_controller --> app.inners.models.entities.role
app.outers.interfaces.deliveries.controllers.role_controller --> app.inners.models.value_objects.contracts.requests.managements.roles.create_body
app.outers.interfaces.deliveries.controllers.role_controller --> app.inners.models.value_objects.contracts.requests.managements.roles.create_one_request
app.outers.interfaces.deliveries.controllers.role_controller --> app.inners.models.value_objects.contracts.requests.managements.roles.delete_one_by_id_request
app.outers.interfaces.deliveries.controllers.role_controller --> app.inners.models.value_objects.contracts.requests.managements.roles.patch_body
app.outers.interfaces.deliveries.controllers.role_controller --> app.inners.models.value_objects.contracts.requests.managements.roles.patch_one_by_id_request
app.outers.interfaces.deliveries.controllers.role_controller --> app.inners.models.value_objects.contracts.requests.managements.roles.read_all_request
app.outers.interfaces.deliveries.controllers.role_controller --> app.inners.models.value_objects.contracts.requests.managements.roles.read_one_by_id_request
app.outers.interfaces.deliveries.controllers.role_controller --> app.inners.models.value_objects.contracts.responses.content
app.outers.interfaces.deliveries.controllers.role_controller --> app.inners.use_cases.managements.role_management
app.outers.interfaces.deliveries.controllers.transaction_controller --> app.inners.models.entities.transaction
app.outers.interfaces.deliveries.controllers.transaction_controller --> app.inners.models.value_objects.contracts.requests.managements.transactions.create_body
app.outers.interfaces.deliveries.controllers.transaction_controller --> app.inners.models.value_objects.contracts.requests.managements.transactions.create_one_request
app.outers.interfaces.deliveries.controllers.transaction_controller --> app.inners.models.value_objects.contracts.requests.managements.transactions.delete_one_by_id_request
app.outers.interfaces.deliveries.controllers.transaction_controller --> app.inners.models.value_objects.contracts.requests.managements.transactions.patch_body
app.outers.interfaces.deliveries.controllers.transaction_controller --> app.inners.models.value_objects.contracts.requests.managements.transactions.patch_one_by_id_request
app.outers.interfaces.deliveries.controllers.transaction_controller --> app.inners.models.value_objects.contracts.requests.managements.transactions.read_all_request
app.outers.interfaces.deliveries.controllers.transaction_controller --> app.inners.models.value_objects.contracts.requests.managements.transactions.read_one_by_id_request
app.outers.interfaces.deliveries.controllers.transaction_controller --> app.inners.models.value_objects.contracts.responses.content
app.outers.interfaces.deliveries.controllers.transaction_controller --> app.inners.use_cases.managements.transaction_management
app.outers.interfaces.deliveries.controllers.transaction_item_map_controller --> app.inners.models.entities.transaction_item_map
app.outers.interfaces.deliveries.controllers.transaction_item_map_controller --> app.inners.models.value_objects.contracts.requests.managements.transaction_item_maps.create_body
app.outers.interfaces.deliveries.controllers.transaction_item_map_controller --> app.inners.models.value_objects.contracts.requests.managements.transaction_item_maps.create_one_request
app.outers.interfaces.deliveries.controllers.transaction_item_map_controller --> app.inners.models.value_objects.contracts.requests.managements.transaction_item_maps.delete_one_by_id_request
app.outers.interfaces.deliveries.controllers.transaction_item_map_controller --> app.inners.models.value_objects.contracts.requests.managements.transaction_item_maps.patch_body
app.outers.interfaces.deliveries.controllers.transaction_item_map_controller --> app.inners.models.value_objects.contracts.requests.managements.transaction_item_maps.patch_one_by_id_request
app.outers.interfaces.deliveries.controllers.transaction_item_map_controller --> app.inners.models.value_objects.contracts.requests.managements.transaction_item_maps.read_one_by_id_request
app.outers.interfaces.deliveries.controllers.transaction_item_map_controller --> app.inners.models.value_objects.contracts.requests.managements.transactions.read_all_request
app.outers.interfaces.deliveries.controllers.transaction_item_map_controller --> app.inners.models.value_objects.contracts.responses.content
app.outers.interfaces.deliveries.controllers.transaction_item_map_controller --> app.inners.use_cases.managements.transaction_item_map_management
app.outers.interfaces.deliveries.routers.api_router --> app.outers.interfaces.deliveries.routers.api_v1_router
app.outers.interfaces.deliveries.routers.api_v1_router --> app.outers.interfaces.deliveries.controllers
app.outers.interfaces.deliveries.routers.api_v1_router --> app.outers.interfaces.deliveries.controllers.account_controller
app.outers.interfaces.deliveries.routers.api_v1_router --> app.outers.interfaces.deliveries.controllers.authentication_controller
app.outers.interfaces.deliveries.routers.api_v1_router --> app.outers.interfaces.deliveries.controllers.company_controller
app.outers.interfaces.deliveries.routers.api_v1_router --> app.outers.interfaces.deliveries.controllers.file_controller
app.outers.interfaces.deliveries.routers.api_v1_router --> app.outers.interfaces.deliveries.controllers.forecast_controller
app.outers.interfaces.deliveries.routers.api_v1_router --> app.outers.interfaces.deliveries.controllers.inventory_control_controller
app.outers.interfaces.deliveries.routers.api_v1_router --> app.outers.interfaces.deliveries.controllers.item_bundle_map_controller
app.outers.interfaces.deliveries.routers.api_v1_router --> app.outers.interfaces.deliveries.controllers.item_controller
app.outers.interfaces.deliveries.routers.api_v1_router --> app.outers.interfaces.deliveries.controllers.item_file_map_controller
app.outers.interfaces.deliveries.routers.api_v1_router --> app.outers.interfaces.deliveries.controllers.location_controller
app.outers.interfaces.deliveries.routers.api_v1_router --> app.outers.interfaces.deliveries.controllers.role_controller
app.outers.interfaces.deliveries.routers.api_v1_router --> app.outers.interfaces.deliveries.controllers.transaction_controller
app.outers.interfaces.deliveries.routers.api_v1_router --> app.outers.interfaces.deliveries.controllers.transaction_item_map_controller
app.outers.repositories.account_repository --> app.inners.models.entities.account
app.outers.repositories.account_repository --> app.outers.utilities.datastore_utility
app.outers.repositories.company_repository --> app.inners.models.entities.company
app.outers.repositories.company_repository --> app.outers.utilities.datastore_utility
app.outers.repositories.file_repository --> app.inners.models.entities.file
app.outers.repositories.file_repository --> app.outers.utilities.datastore_utility
app.outers.repositories.inventory_control_repository --> app.inners.models.entities.inventory_control
app.outers.repositories.inventory_control_repository --> app.outers.utilities.datastore_utility
app.outers.repositories.item_bundle_map_repository --> app.inners.models.entities.item_bundle_map
app.outers.repositories.item_bundle_map_repository --> app.outers.utilities.datastore_utility
app.outers.repositories.item_file_map_repository --> app.inners.models.entities.item_file_map
app.outers.repositories.item_file_map_repository --> app.outers.utilities.datastore_utility
app.outers.repositories.item_repository --> app.inners.models.entities.item
app.outers.repositories.item_repository --> app.outers.utilities.datastore_utility
app.outers.repositories.location_repository --> app.inners.models.entities.location
app.outers.repositories.location_repository --> app.outers.utilities.datastore_utility
app.outers.repositories.role_repository --> app.inners.models.entities.role
app.outers.repositories.role_repository --> app.outers.utilities.datastore_utility
app.outers.repositories.transaction_item_map_repository --> app.inners.models.entities.transaction_item_map
app.outers.repositories.transaction_item_map_repository --> app.inners.models.value_objects.forecasts.transaction_item_map_forecast
app.outers.repositories.transaction_item_map_repository --> app.outers.utilities.datastore_utility
app.outers.repositories.transaction_repository --> app.inners.models.entities.transaction
app.outers.repositories.transaction_repository --> app.outers.utilities.datastore_utility
app.outers.utilities.datastore_utility --> app.outers.settings.datastore_settings
app.outers.utilities.management_utility --> app.inners.models.entities.base_entity
@enduml
